### ISSUE TITLE
to-do Improve visualization in plots

### ISSUE THREAD

**Issue by PankyThakur** [MFirasatHussain/WalletBuddy#1]
Issue #1 in '/trend': The plots for this feature are not readable. Visualization should be neat and clear.
Issue #1 in '/predict': The summary lacks the ml-model output insight metric, like accuracy/error margin band.

**Comment by utkarsh-us-sharmaa** [comment]
Added both the things:
1. formatted the plot fonts to make it more readable
2. error margin band visible now
